
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
    default-schema: voting-system
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${STACKHERO_MYSQL_HOST:localhost}:${STACKHERO_MYSQL_PORT:3306}/voting-system?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${STACKHERO_MYSQL_USER:root}
    password: ${STACKHERO_MYSQL_ROOT_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /api-docs
